version: '3.1'

volumes:
  db_data:
  db_logs:
  db_conf:

services:
  db:
    image: mariadb:10.6.10
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: routemanager
    volumes:
      - db_data:/var/lib/mysql/data
      - db_logs:/var/lib/mysql/logs
      - db_conf:/var/docker/mariadb/conf
    ports:
      - 3306:3306
