version: '3.1'

volumes:
  db_data:
  db_logs:
  db_conf:
  es_data:
  kibana_data:

networks:
  route-manager:

services:
  db:
    image: mariadb:10.6.10
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: routemanager
    volumes:
      - db_data:/var/lib/mysql/data
      - db_logs:/var/lib/mysql/logs
      - db_conf:/var/docker/mariadb/conf
    networks:
      - route-manager
    ports:
      - 3306:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      xpack.security.enabled: "false"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - route-manager
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    environment:
      # https://www.elastic.co/guide/en/kibana/current/settings.html
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - route-manager
    ports:
      - 5601:5601
